Update build-openwrt24.1.yml

diff --git a/.github/workflows/build-openwrt24.1.yml b/.github/workflows/build-openwrt24.1.yml
--- a/.github/workflows/build-openwrt24.1.yml
+++ b/.github/workflows/build-openwrt24.1.yml
@@ -1,138 +1,143 @@
-name: Build immortalwrt24.10  rax3000m_nand
+name: build-cudy-24.10.0
 
 on:
-  repository_dispatch:
   workflow_dispatch:
+    inputs:
+      profile:
+        type: choice
+        description: "请选择路由器型号"
+        required: true
+        options:
+          - cudy_tr3000-v1
+          - cudy_tr3000-v1-ubootmod
+        default: cudy_tr3000-v1
+      include_docker:
+        description: |
+          是否编译 Docker 插件
+        required: true
+        default: 'no'
+        type: choice
+        options:
+          - 'yes'
+          - 'no'
 
-env:
-  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
-  REPO_BRANCH: 2410
-  FEEDS_CONF: feeds.conf.default
-  CONFIG_FILE: .config
-  DIY_P1_SH: diy-part1.sh
-  DIY_P2_SH: diy-part2.sh
-  UPLOAD_BIN_DIR: false
-  UPLOAD_FIRMWARE: true
-  UPLOAD_RELEASE: true
-  TZ: Asia/Shanghai
+permissions:
+  contents: write
 
 jobs:
   build:
     runs-on: ubuntu-22.04
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@main
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
-        sudo docker image prune --all --force
-        sudo -E apt-get update -qq
-        sudo -E apt-get install -y --no-install-recommends \
-          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
-          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext \
-          gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool \
-          lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev \
-          libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev \
-          libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch \
-          pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools \
-          qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo \
-          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
-        sudo -E apt-get clean
-        sudo timedatectl set-timezone "$TZ"
-        sudo mkdir -p /workdir
-        sudo chown $USER:$GROUPS /workdir
+      - name: Set executable permissions
+        run: |
+          chmod +x ${{ github.workspace }}/public/filogic/build-24.sh
+          chmod +x ${{ github.workspace }}/public/ramips/build-24.sh
 
-    - name: Clone source code
-      working-directory: /workdir
-      run: |
-        df -hT $PWD
-        git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
-        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
+      - name: Get current router model name and set to environment variable
+        run: |
+          if [ "${{ github.event.inputs.profile }}" = "cudy_tr3000-v1" ]; then
+            MODEL="TR3000-V1"
+          elif [ "${{ github.event.inputs.profile }}" = "cudy_tr3000-v1-ubootmod" ]; then
+            MODEL="TR3000-V1-UbootMod"
+          else
+            echo "Error: Invalid profile selected!"
+            exit 1
+          fi
+          echo "MODEL=$MODEL" >> $GITHUB_ENV
 
-    - name: Load custom feeds
-      run: |
-        [ -e $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default
-        chmod +x $GITHUB_WORKSPACE/$DIY_P1_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P1_SH
+      - name: Build Cudy ImmortalWrt 24.10.0
+        run: |
+          profiles="${{ github.event.inputs.profile }}"
+          include_docker="${{ github.event.inputs.include_docker }}"
 
-    - name: Update feeds
-      run: |
-        cd openwrt
-        ./scripts/feeds update -a
-        rm -rf feeds/luci/applications/luci-app-mosdns
-        rm -rf feeds/packages/net/{alist,adguardhome,mosdns,xray*,v2ray*,sing*,smartdns}
-        rm -rf feeds/packages/utils/v2dat
-        rm -rf feeds/packages/lang/golang
-        git clone https://github.com/kenzok8/golang feeds/packages/lang/golang
+          if [ "$profiles" = "cudy_tr3000-v1" ]; then
+            tag=mediatek-filogic-openwrt-24.10.0
+            build_script="public/filogic/build-24.sh"
+            echo "platform=mediatek/filogic" >> $GITHUB_ENV
+          elif [ "$profiles" = "cudy_tr3000-v1-ubootmod" ]; then
+            tag=mediatek-filogic-openwrt-24.10.0
+            build_script="public/filogic/build-24.sh"
+            echo "platform=mediatek/filogic" >> $GITHUB_ENV
+          fi
 
-    - name: Install feeds
-      run: |
-        cd openwrt
-        ./scripts/feeds install -a 
+          IFS=',' read -r -a profile_array <<< "$profiles"
 
-    - name: Load custom configuration
-      run: |
-        [ -e files ] && cp -r files openwrt/files
-        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
-        chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P2_SH
+          for profile in "${profile_array[@]}"; do
+            echo "Building for profile: $profile"
 
-    - name: Download package
-      id: package
-      run: |
-        cd openwrt
-        make defconfig
-        make download -j8
-        find dl -size -1024c -exec ls -l {} \;
-        find dl -size -1024c -exec rm -f {} \;
+            docker run --rm -i \
+              --user root \
+              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
+              -v "${{ github.workspace }}/files/etc/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
+              -v "${{ github.workspace }}/$build_script:/home/build/immortalwrt/build.sh" \
+              -e PROFILE=$profile \
+              -e INCLUDE_DOCKER=$include_docker \
+              immortalwrt/imagebuilder:$tag /bin/bash /home/build/immortalwrt/build.sh
+          done
 
-    - name: Compile the firmware
-      id: compile
-      run: |
-        cd openwrt
-        echo -e "$(nproc) threads compiling"
-        make -j$(($(nproc) + 1)) || make -j1 V=s
-        echo "status=success" >> $GITHUB_OUTPUT
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
-        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-        cat $GITHUB_ENV
+      - name: Generate Firmware SHA-256
+        run: |
+          tree ${{ github.workspace }}/bin/targets/${{ env.platform }}
+          cp -r ${{ github.workspace }}/bin/targets/${{ env.platform }}/*.bin ${{ github.workspace }}
+          for file in *.bin; do
+            sha256sum "$file" > "$file.sha256"
+            sha256sum -c "$file.sha256"
+          done
+          if [ "${{ github.event.inputs.profile }}" = "cudy_tr3000-v1-ubootmod" ]; then
+            cp -r ${{ github.workspace }}/bin/targets/${{ env.platform }}/*.fip ${{ github.workspace }}
+            cp -r ${{ github.workspace }}/bin/targets/${{ env.platform }}/*.itb ${{ github.workspace }}
+            for file in *.fip; do
+              sha256sum "$file" > "$file.sha256"
+              sha256sum -c "$file.sha256"
+            done
+            for file in *.itb; do
+              sha256sum "$file" > "$file.sha256"
+              sha256sum -c "$file.sha256"
+            done
+          fi
 
-    - name: Check space usage
-      if: (!cancelled())
-      run: df -hT
+      - name: Generate release informations
+        run: |
+          TIME="$(curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | jq -r .created_at)"
 
-    - name: Upload bin directory
-      uses: actions/upload-artifact@main
-      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
-      with:
-        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: openwrt/bin
+          RELEASE_TAG="ImmortalWrt-24.10.0-Cudy-${{ env.MODEL }}-$(date -d "${TIME}" -u +'%Y-%m-%d')"
+          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
 
-    - name: Organize files
-      id: organize
-      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
-      run: |
-        FIRMWARE_PATH=$(find openwrt/bin/targets -type d | head -n 1)
-        echo "FIRMWARE=$FIRMWARE_PATH" >> $GITHUB_ENV
-        echo "status=success" >> $GITHUB_OUTPUT
+          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
+            IS_DOCKER="是"
+          else
+            IS_DOCKER="否"
+          fi
 
-    - name: Upload firmware directory
-      uses: actions/upload-artifact@main
-      if: steps.organize.outputs.status == 'success' && !cancelled()
-      with:
-        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: ${{ env.FIRMWARE }}
+          cat <<EOF | sed -E 's/^  //' > Release.md
+            CI ImmortalWrt-24.10.0-Cudy-${{ env.MODEL }} $(date -d "${TIME}" -u +'%Y-%m-%d %H:%M:%S %Z(%:z)')
 
-    - name: Generate release tag
-      id: tag
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-      run: |
-        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
-        touch 2410
+            构建时间：\`$(date -d "${TIME}" -u +'%Y-%m-%d %H:%M:%S %Z(%:z)')\`
+            构建版本：ImmortalWrt-24.10.0
+            是否内置 Docker ：$IS_DOCKER
+            登录后台：\`192.168.100.1\`
+            用户名：\`root\`
+            密码：无
+          EOF
+
+          echo "RELEASE_NAME=$(head --line=1 Release.md)" >> $GITHUB_ENV
+          tail --line=+2 Release.md > Body.md
+
+      - name: Upload ImmortalWrt as release assets
+        uses: softprops/action-gh-release@v2.2.1
+        with:
+          tag_name: ${{ env.RELEASE_TAG }}
+          name: ${{ env.RELEASE_NAME }}
+          body_path: ${{ github.workspace }}/Body.md
+          files: |
+            ${{ github.workspace }}/*.fip
+            ${{ github.workspace }}/*.itb
+            ${{ github.workspace }}/*.bin
+            ${{ github.workspace }}/*.sha256
+          token: ${{ secrets.GITHUB_TOKEN }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
